In [1]:
import pandas as pd


In [2]:
df = pd.read_csv(r"archive/diabetes.csv")

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


## Define Input and Target

In [6]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [7]:
y = df.pop('Outcome')

In [8]:
X = df

In [9]:
X.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

## Train -test 

In [11]:
from sklearn.model_selection import train_test_split

In [16]:
len(df)

768

In [17]:
768*.33

253.44

In [18]:
768-253

515

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
X_train.shape

(514, 8)

In [14]:
y_train.shape

(514,)

In [15]:
X_test.shape

(254, 8)

## Train the model

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
model = LogisticRegression(solver='liblinear')

## Fit the model

In [21]:
model.fit(X_train,y_train)

LogisticRegression(solver='liblinear')

## See the Constants

In [22]:
model.coef_

array([[ 0.06004713,  0.02613134, -0.01651426, -0.00170015, -0.0002897 ,
         0.06352444,  0.21816992,  0.0216512 ]])

In [23]:
model.intercept_

array([-5.71319873])

### Get the Predictions

In [24]:
y_pred = model.predict(X_test)

In [25]:
X_test


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
668            6       98             58             33      190  34.0   
324            2      112             75             32        0  35.7   
624            2      108             64              0        0  30.8   
690            8      107             80              0        0  24.6   
473            7      136             90              0        0  29.9   
..           ...      ...            ...            ...      ...   ...   
311            0      106             70             37      148  39.4   
429            1       95             82             25      180  35.0   
182            1        0             74             20       23  27.7   
586            8      143             66              0        0  34.9   
679            2      101             58             17      265  24.2   

     DiabetesPedigreeFunction  Age  
668                     0.430   43  
324                     0.148   21  
624                     0.158   21  
690                     0.856   34  
473                     0.210   50  
..                        ...  ...  
311                     0.605   22  
429                     0.233   43  
182                     0.299   21  
586                     0.129   41  
679                     0.614   23  

[254 rows x 8 columns]

In [26]:
y_pred[250]

0

In [27]:
y_test.iloc[250]

1

In [28]:
from sklearn.metrics import f1_score,confusion_matrix,classification_report

In [29]:
f1_score(y_true=y_test,y_pred=y_pred)

0.6424242424242425

In [30]:
res= pd.DataFrame(y_pred,columns=['y_pred'])

In [31]:
res['y_test']=y_test.values

In [32]:
res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   y_pred  254 non-null    int64
 1   y_test  254 non-null    int64
dtypes: int64(2)
memory usage: 4.1 KB


In [33]:
len(res[(res['y_pred']==0) & (res['y_test']==1)])

33

In [34]:
import numpy as np

In [35]:
confusion_matrix(y_true=y_test,y_pred=y_pred)

array([[142,  26],
       [ 33,  53]], dtype=int64)

In [36]:
cr = classification_report(y_true=y_test,y_pred=y_pred)

In [37]:
print(cr)

              precision    recall  f1-score   support

           0       0.81      0.85      0.83       168
           1       0.67      0.62      0.64        86

    accuracy                           0.77       254
   macro avg       0.74      0.73      0.74       254
weighted avg       0.76      0.77      0.77       254

